// Typecheck the module-sources tree against a recorded baseline.
//
// `tsc -p tsconfig.modules.json` cannot reach zero errors, and that is not a
// defect in the modules: module-sources compiles against the Prisma client
// generated from prisma/schema.prisma, which contains ONLY core models. Every
// model a module ships in its own schema.prisma (Order, Coupon, WheelPrize, …)
// is therefore missing from PrismaClient, and each use of one is an error. A
// zero-error run would require generating a client from core + all 42 module
// schemas, which is exactly the merged schema core must NOT ship.
//
// So the gate is a delta: errors already in the baseline are tolerated, any
// NEW error fails. Line/column numbers are stripped before comparing so that
// unrelated edits above an error do not produce phantom diffs.
//
// Refresh the baseline with `npm run typecheck:modules -- --update` after
// deliberately changing the module tree.

import { spawnSync } from "child_process";
import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const BASELINE = path.join(ROOT, "module-sources/.typecheck-baseline.txt");
const SOURCES = path.join(ROOT, "module-sources");
// Sits at the root of module-sources, not inside any module: it must not end
// up in a ZIP, and the boundary scanners only walk module directories.
const CONTRACTS = path.join(SOURCES, "__hook-contracts__.ts");
const update = process.argv.includes("--update");

/**
 * A `hookListeners` entry is wired by codegen through a dynamic import, so the
 * handler's signature is erased and nothing checks it against the payload the
 * hook actually carries. This file re-states each of those wirings as a
 * type-level assertion, which typechecks the two halves against each other.
 *
 * It is generated per run and deleted afterwards: it names handlers across
 * module boundaries, which is exactly what a shipped module must never do.
 */
function writeHookContracts(): number {
    const lines: string[] = [
        "// AUTO-GENERATED by scripts/typecheck-modules.ts — deleted after the run.",
        "// Each line asserts that a module's declared hook listener accepts the",
        "// payload its hook is declared to carry. Do not edit or commit.",
        'import type { AssertHookHandler, Expect } from "@/core/sdk";',
        "",
    ];
    let count = 0;

    for (const id of fs.readdirSync(SOURCES).sort()) {
        const manifestPath = path.join(SOURCES, id, "module.json");
        if (!fs.existsSync(manifestPath)) continue;

        let manifest: { hookListeners?: { hook: string; type: string; handler: string }[] };
        try {
            manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
        } catch {
            continue; // a broken manifest is reported by validate:module, not here
        }

        for (const listener of manifest.hookListeners ?? []) {
            const specifier = `./${id}/${listener.handler}`.replace(/\.tsx?$/, "");
            lines.push(
                `// ${id}: ${listener.hook}`,
                `type Contract${count} = Expect<AssertHookHandler<`,
                `    "${listener.hook}",`,
                `    "${listener.type}",`,
                `    typeof import("${specifier}").default`,
                ">>;",
                "",
            );
            count++;
        }
    }

    fs.writeFileSync(CONTRACTS, lines.join("\n"), "utf-8");
    return count;
}

const contractCount = writeHookContracts();

let raw: string;
try {
    const run = spawnSync("npx", ["tsc", "--noEmit", "-p", "tsconfig.modules.json"], {
        cwd: ROOT,
        encoding: "utf-8",
        maxBuffer: 32 * 1024 * 1024,
    });
    raw = `${run.stdout ?? ""}${run.stderr ?? ""}`;
} finally {
    fs.rmSync(CONTRACTS, { force: true });
}
const errors = raw
    .split("\n")
    .filter((l) => / error TS\d+: /.test(l))
    // Drop the (line,col) so the baseline survives unrelated edits in the file.
    .map((l) => l.replace(/\(\d+,\d+\)/, ""))
    // Drop inlined type printouts. TypeScript spells whole object types into
    // the message ("does not exist on type '{ id: string; email: … }'"), and
    // their field order changes every time the Prisma client is regenerated —
    // which would invalidate the entire baseline for no real change. Short
    // quoted names (the property that is actually missing) are kept.
    //
    // The generated contracts file is exempt: there the spelled-out type IS the
    // diagnostic — it names the hook, the payload the emitter promises and the
    // one the listener wants — and it is regenerated per run, so it can never
    // go stale in the baseline.
    .map((l) => (l.includes("__hook-contracts__") ? l : l.replace(/'[^']{60,}'|'[^']*;[^']*'/g, "'…'")))
    .sort();

if (update) {
    fs.writeFileSync(BASELINE, errors.join("\n") + (errors.length ? "\n" : ""), "utf-8");
    console.log(`Baseline updated: ${errors.length} known error(s) recorded.`);
    process.exit(0);
}

if (!fs.existsSync(BASELINE)) {
    console.error(`No baseline at ${path.relative(ROOT, BASELINE)}. Run: npm run typecheck:modules -- --update`);
    process.exit(1);
}

const known = new Map<string, number>();
for (const line of fs.readFileSync(BASELINE, "utf-8").split("\n")) {
    if (line.trim()) known.set(line, (known.get(line) ?? 0) + 1);
}

const introduced: string[] = [];
for (const err of errors) {
    const left = known.get(err) ?? 0;
    if (left > 0) known.set(err, left - 1);
    else introduced.push(err);
}
const fixed = [...known.values()].reduce((a, b) => a + b, 0);

if (introduced.length > 0) {
    console.error(`${introduced.length} new type error(s) in module-sources:\n`);
    for (const err of introduced) console.error(`  ${err}`);
    if (introduced.some((e) => e.includes("__hook-contracts__"))) {
        console.error(
            "\n  __hook-contracts__.ts is generated from every module's hookListeners:\n" +
            "  an error there means a listener's payload type disagrees with the\n" +
            "  payload the emitting module declares in its UxwVendHookPayloads block.",
        );
    }
    console.error(`\n(${errors.length - introduced.length} pre-existing error(s) tolerated — see the header of scripts/typecheck-modules.ts.)`);
    process.exit(1);
}

console.log(
    `module-sources: no new type errors (${errors.length} known, see module-sources/.typecheck-baseline.txt); ` +
    `${contractCount} hook listener contract(s) verified.`,
);
if (fixed > 0) {
    console.log(`${fixed} baseline error(s) no longer occur — refresh with: npm run typecheck:modules -- --update`);
}
