// Typecheck module-sources/ — the 24k lines the main tsconfig excludes.
//
// The exclusion in tsconfig.json is deliberate: a module imports
// `@/modules/<id>/...` paths that exist only once it is installed. But the
// consequence was that module code was never type-checked by anything.
//
// The hard part is Prisma. `module-sources` compiles against the client
// generated from `prisma/schema.prisma`, which holds only the models of the
// modules that happen to be INSTALLED — normally none. Every reference to a
// module's own model (Order, Coupon, WheelPrize, …) is then a "does not exist
// on PrismaClient" error. This script used to tolerate 503 such errors through
// a recorded baseline, which meant real errors could hide among them, and two
// did.
//
// So instead of tolerating them, remove their cause: generate a throwaway
// Prisma client from core + EVERY module-sources schema, point `@prisma/client`
// at it for the duration of the run, and demand zero errors. Nothing about this
// client is shipped — core must not carry models for modules nobody installed —
// and it is regenerated only when the merged schema actually changes.

import { spawnSync } from "child_process";
import crypto from "crypto";
import fs from "fs";
import path from "path";
import { mergeSchemas } from "./lib/merge-prisma-schemas";

const ROOT = process.cwd();
const SOURCES = path.join(ROOT, "module-sources");
const WORK_DIR = path.join(ROOT, ".typecheck-modules");
const CLIENT_DIR = path.join(WORK_DIR, "client");
const SCHEMA_PATH = path.join(WORK_DIR, "schema.prisma");
const STAMP_PATH = path.join(WORK_DIR, "schema.hash");
const TSCONFIG_PATH = path.join(ROOT, "tsconfig.modules.generated.json");
// Sits at the root of module-sources, not inside any module: it must not end
// up in a ZIP, and the boundary scanners only walk module directories.
const CONTRACTS = path.join(SOURCES, "__hook-contracts__.ts");

/**
 * A `hookListeners` entry is wired by codegen through a dynamic import, so the
 * handler's signature is erased and nothing checks it against the payload the
 * hook actually carries. This file re-states each of those wirings as a
 * type-level assertion, which typechecks the two halves against each other.
 *
 * It is generated per run and deleted afterwards: it names handlers across
 * module boundaries, which is exactly what a shipped module must never do.
 */
function writeHookContracts(): number {
    const lines: string[] = [
        "// AUTO-GENERATED by scripts/typecheck-modules.ts — deleted after the run.",
        "// Each line asserts that a module's declared hook listener accepts the",
        "// payload its hook is declared to carry. Do not edit or commit.",
        'import type { AssertHookHandler, Expect } from "@/core/sdk";',
        "",
    ];
    let count = 0;

    for (const id of fs.readdirSync(SOURCES).sort()) {
        const manifestPath = path.join(SOURCES, id, "module.json");
        if (!fs.existsSync(manifestPath)) continue;

        let manifest: { hookListeners?: { hook: string; type: string; handler: string }[] };
        try {
            manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
        } catch {
            continue; // a broken manifest is reported by validate:module, not here
        }

        for (const listener of manifest.hookListeners ?? []) {
            const specifier = `./${id}/${listener.handler}`.replace(/\.tsx?$/, "");
            lines.push(
                `// ${id}: ${listener.hook}`,
                `type Contract${count} = Expect<AssertHookHandler<`,
                `    "${listener.hook}",`,
                `    "${listener.type}",`,
                `    typeof import("${specifier}").default`,
                ">>;",
                "",
            );
            count++;
        }
    }

    fs.writeFileSync(CONTRACTS, lines.join("\n"), "utf-8");
    return count;
}

/**
 * Generate the all-modules Prisma client, skipping the work when the merged
 * schema is byte-identical to the one already generated. `prisma generate` is
 * the slowest step here by an order of magnitude, and the schema only changes
 * when a module's models do.
 */
function ensureMergedClient(): { modules: number; models: number; regenerated: boolean } {
    const merged = mergeSchemas(ROOT, "all-sources");
    for (const warning of merged.warnings) console.warn(`[typecheck-modules] WARNING: ${warning}`);

    // The core generator block has no `output`, which lands the client in
    // node_modules and would clobber the real one.
    const schema = merged.schema.replace(
        /generator\s+client\s*\{[^}]*\}/,
        `generator client {\n  provider = "prisma-client-js"\n  output   = "${CLIENT_DIR}"\n}`,
    );
    const hash = crypto.createHash("sha256").update(schema).digest("hex");

    fs.mkdirSync(WORK_DIR, { recursive: true });
    const fresh =
        fs.existsSync(CLIENT_DIR) &&
        fs.existsSync(STAMP_PATH) &&
        fs.readFileSync(STAMP_PATH, "utf-8").trim() === hash;

    if (!fresh) {
        fs.writeFileSync(SCHEMA_PATH, schema, "utf-8");
        const gen = spawnSync("npx", ["prisma", "generate", "--schema", SCHEMA_PATH], {
            cwd: ROOT,
            encoding: "utf-8",
            timeout: 180_000,
        });
        if (gen.status !== 0) {
            console.error("prisma generate failed for the merged module schema:\n");
            console.error(`${gen.stdout ?? ""}${gen.stderr ?? ""}`);
            process.exit(1);
        }
        fs.writeFileSync(STAMP_PATH, hash, "utf-8");
    }

    return { modules: merged.moduleNames.length, models: merged.modelCount, regenerated: !fresh };
}

function writeTsconfig(): void {
    // Written at the repo root, not inside WORK_DIR: `extends`, `include` and
    // `paths` all resolve relative to the file that declares them, so moving it
    // a directory down would silently repoint every glob.
    const config = {
        "//": `GENERATED by scripts/typecheck-modules.ts — do not edit or commit. Points @prisma/client at ${path.relative(ROOT, CLIENT_DIR)}, a client generated from core plus every module-sources schema.`,
        extends: "./tsconfig.modules.json",
        compilerOptions: {
            // `paths` replaces rather than merges, so the base mapping is restated.
            paths: {
                "@/*": ["./src/*"],
                "@prisma/client": [`./${path.relative(ROOT, CLIENT_DIR)}`],
                "@prisma/client/*": [`./${path.relative(ROOT, CLIENT_DIR)}/*`],
            },
        },
    };
    fs.writeFileSync(TSCONFIG_PATH, JSON.stringify(config, null, 2) + "\n", "utf-8");
}

const client = ensureMergedClient();
writeTsconfig();
const contractCount = writeHookContracts();

let raw: string;
try {
    const run = spawnSync("npx", ["tsc", "--noEmit", "-p", path.basename(TSCONFIG_PATH)], {
        cwd: ROOT,
        encoding: "utf-8",
        maxBuffer: 32 * 1024 * 1024,
    });
    raw = `${run.stdout ?? ""}${run.stderr ?? ""}`;
} finally {
    fs.rmSync(CONTRACTS, { force: true });
}

const errors = raw.split("\n").filter((l) => / error TS\d+: /.test(l));

if (errors.length > 0) {
    console.error(`${errors.length} type error(s) in module-sources:\n`);
    for (const err of errors) console.error(`  ${err}`);
    if (errors.some((e) => e.includes("__hook-contracts__"))) {
        console.error(
            "\n  __hook-contracts__.ts is generated from every module's hookListeners:\n" +
                "  an error there means a listener's payload type disagrees with the\n" +
                "  payload the emitting module declares in its UxwVendHookPayloads block.",
        );
    }
    process.exit(1);
}

console.log(
    `module-sources: 0 type errors across ${client.modules} module schema(s) / ${client.models} models` +
        `${client.regenerated ? " (client regenerated)" : ""}; ` +
        `${contractCount} hook listener contract(s) verified.`,
);
